[package]
name = "psign-opc-sign"
version = "0.6.3"
edition = "2024"
description = "Portable OPC, VSIX, and NuGet package signing primitives"
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1"
base64 = "0.22"
sha2 = "0.11"
time = { version = "0.3", features = ["local-offset"] }
zip = { version = "0.6.6", default-features = false, features = ["deflate"] }
